export const ARMS_REGIONS = [
  'armpits',
  'leftArmpit',
  'rightArmpit',
  'arms',
  'leftArm',
  'rightArm',
  'leftUpperArm',
  'rightUpperArm',
  'leftElbow',
  'rightElbow',
  'leftForearm',
  'rightForearm',
  'leftWrist',
  'rightWrist',
  'hands',
  'leftHand',
  'rightHand',
  'leftPalm',
  'rightPalm',
  'leftFingers',
  'rightFingers',
] as const;
