/**
 * NPC Availability Schemas
 *
 * Tracks whether NPCs can be interacted with (sleeping, traveling, busy).
 * Enables wake-up mechanics and interaction blocking.
 *
 * @see dev-docs/32-npc-encounters-and-occupancy.md Section 6
 */
import { z } from 'zod';
import { type AffinityScores } from './awareness.js';
import type { NpcTier } from '../npc-tier/types.js';

// =============================================================================
// Unavailability Reason
// =============================================================================

/**
 * Why an NPC is unavailable for interaction.
 */
export const UnavailabilityReasonSchema = z.enum(['sleeping', 'traveling', 'busy', 'inaccessible']);
export type UnavailabilityReason = z.infer<typeof UnavailabilityReasonSchema>;

// =============================================================================
// NPC Availability
// =============================================================================

/**
 * Whether an NPC can be interacted with.
 */
export const NpcAvailabilitySchema = z.object({
  /** Whether the NPC is available for interaction */
  available: z.boolean(),

  /** Why the NPC is unavailable (if unavailable) */
  reason: UnavailabilityReasonSchema.optional(),

  /** Whether the player can override the unavailability */
  canOverride: z.boolean(),

  /** Consequences of overriding (for player info/LLM prompt) */
  overrideConsequences: z.string().optional(),
});
export type NpcAvailability = z.infer<typeof NpcAvailabilitySchema>;

// =============================================================================
// Availability Calculation
// =============================================================================

/**
 * Input for availability check.
 */
export interface AvailabilityInput {
  /** NPC tier */
  tier: NpcTier;

  /** Current activity type */
  activityType: string;

  /** Current engagement level */
  engagement: 'idle' | 'casual' | 'focused' | 'absorbed';

  /** NPC's current location */
  npcLocationId: string;

  /** Player's current location */
  playerLocationId: string;
}

/**
 * Determine if an NPC can be interacted with.
 */
export function checkAvailability(input: AvailabilityInput): NpcAvailability {
  const { tier, activityType, engagement, npcLocationId, playerLocationId } = input;
  const sameLocation = npcLocationId === playerLocationId;

  // Sleeping check
  if (activityType === 'sleeping') {
    if (tier === 'major') {
      return {
        available: false,
        reason: 'sleeping',
        canOverride: true,
        overrideConsequences: 'They will be woken and may react based on relationship',
      };
    }

    if (tier === 'minor' && sameLocation) {
      return {
        available: false,
        reason: 'sleeping',
        canOverride: true,
        overrideConsequences: 'You can wake them, but they may be grumpy',
      };
    }

    return {
      available: false,
      reason: 'sleeping',
      canOverride: false,
    };
  }

  // Traveling check
  if (activityType === 'traveling') {
    return {
      available: false,
      reason: 'traveling',
      canOverride: false,
    };
  }

  // Absorbed in activity - can interrupt but may annoy
  if (engagement === 'absorbed') {
    return {
      available: true,
      reason: 'busy',
      canOverride: true,
      overrideConsequences: 'Interrupting may annoy them',
    };
  }

  // Available
  return { available: true, canOverride: true };
}

// =============================================================================
// Wake-Up Reaction
// =============================================================================

/**
 * Mood when woken up.
 */
export const WakeUpMoodSchema = z.enum(['groggy', 'annoyed', 'alarmed', 'pleased', 'angry']);
export type WakeUpMood = z.infer<typeof WakeUpMoodSchema>;

/**
 * Reaction when an NPC is woken up.
 */
export const WakeUpReactionSchema = z.object({
  /** Mood upon waking */
  mood: WakeUpMoodSchema,

  /** Optional dialogue hint (generated by LLM based on affinity) */
  dialogueHint: z.string().optional(),
});
export type WakeUpReaction = z.infer<typeof WakeUpReactionSchema>;

/**
 * Relationship type for wake-up mood calculation.
 */
export type RelationshipType =
  | 'partner'
  | 'close_friend'
  | 'friend'
  | 'acquaintance'
  | 'stranger'
  | 'rival'
  | 'enemy';

/**
 * Determine wake-up mood based on relationship and affinity.
 */
export function determineWakeUpMood(
  affinity: AffinityScores,
  relationship: RelationshipType,
  urgency: boolean
): WakeUpMood {
  // Close relationship + high affinity = more forgiving
  if (relationship === 'partner' || relationship === 'close_friend') {
    if (affinity.fondness > 60) return urgency ? 'alarmed' : 'pleased';
    return 'groggy';
  }

  // Low affinity = not happy about it
  if (affinity.fondness < 0) return 'angry';
  if (affinity.fondness < 30) return 'annoyed';

  return 'groggy';
}

// =============================================================================
// Default Factory
// =============================================================================

/**
 * Create a default availability (available).
 */
export function createDefaultAvailability(): NpcAvailability {
  return {
    available: true,
    canOverride: true,
  };
}
