import type { HygieneLevel } from '../state/hygiene.js';
import type { BodyRegion } from './regions.js';
import type { RegionScent } from './sensory.js';
import { TOE_REGIONS } from '../body-regions/index.js';

/**
 * Tiered scent defaults.
 *
 * - universal: always safe to default without prompting
 * - hygieneModulated: defaults exist, but descriptions should be modified by hygiene
 * - customizable: defaults are minimal; UI may prompt the user to override
 */
export const SCENT_TIERS = {
  universal: [
    // Head
    'head',
    'face',
    'forehead',
    'leftEye',
    'rightEye',
    'nose',
    'leftCheek',
    'rightCheek',
    'chin',
    'ears',
    'leftEar',
    'rightEar',

    // Neck
    'neck',
    'nape',
    'throat',

    // Upper body
    'shoulders',
    'leftShoulder',
    'rightShoulder',
    'chest',
    'leftPectoral',
    'rightPectoral',
    'upperBack',
    'back',
    'spine',
    'lowerBack',

    // Torso
    'torso',
    'abdomen',
    'navel',
    'leftSide',
    'rightSide',

    // Limbs
    'arms',
    'leftArm',
    'rightArm',
    'hands',
    'leftHand',
    'rightHand',
    'legs',
    'leftLeg',
    'rightLeg',
    'thighs',
    'leftThigh',
    'rightThigh',
    'knees',
    'leftKnee',
    'rightKnee',
    'calves',
    'leftCalf',
    'rightCalf',
    'leftShin',
    'rightShin',
    'ankles',
    'leftAnkle',
    'rightAnkle',
    'feet',
    'leftFoot',
    'rightFoot',
    'leftHeel',
    'rightHeel',
    'leftSole',
    'rightSole',
    'leftArch',
    'rightArch',
    'toes',
  ],
  hygieneModulated: [
    'hair',
    'armpits',
    'leftArmpit',
    'rightArmpit',
    'groin',
    'buttocks',
    'leftButtock',
    'rightButtock',
    'feet',
    'leftFoot',
    'rightFoot',
    'toes',
    ...TOE_REGIONS,
  ],
  customizable: [
    'mouth',
    'breasts',
    'leftBreast',
    'rightBreast',
    'nipples',
    'leftNipple',
    'rightNipple',
    'waist',
    'hips',
    'leftHip',
    'rightHip',
    'anus',
    'penis',
    'vagina',
    'pelvis',
  ],
} as const satisfies Record<string, readonly BodyRegion[]>;

export type ScentTier = keyof typeof SCENT_TIERS;

const CLEAN_SKIN: RegionScent = { primary: 'clean skin', intensity: 0.2 };
const NEUTRAL: RegionScent = { primary: 'neutral', intensity: 0.2 };
const NEUTRAL_FAINT: RegionScent = { primary: 'neutral', intensity: 0.1 };

export const DEFAULT_SCENTS: Partial<Record<BodyRegion, RegionScent>> = {
  // Head
  head: { ...NEUTRAL, intensity: 0.2 },
  face: CLEAN_SKIN,
  forehead: CLEAN_SKIN,
  leftEye: CLEAN_SKIN,
  rightEye: CLEAN_SKIN,
  nose: CLEAN_SKIN,
  leftCheek: CLEAN_SKIN,
  rightCheek: CLEAN_SKIN,
  chin: CLEAN_SKIN,
  mouth: { primary: 'neutral', intensity: 0.15 },
  hair: { primary: 'clean hair', notes: ['shampoo'], intensity: 0.3 },
  ears: { ...CLEAN_SKIN, intensity: 0.15 },
  leftEar: { ...CLEAN_SKIN, intensity: 0.15 },
  rightEar: { ...CLEAN_SKIN, intensity: 0.15 },

  // Neck
  neck: CLEAN_SKIN,
  nape: CLEAN_SKIN,
  throat: CLEAN_SKIN,

  // Upper body
  shoulders: CLEAN_SKIN,
  leftShoulder: CLEAN_SKIN,
  rightShoulder: CLEAN_SKIN,
  chest: CLEAN_SKIN,
  leftPectoral: CLEAN_SKIN,
  rightPectoral: CLEAN_SKIN,
  breasts: CLEAN_SKIN,
  leftBreast: CLEAN_SKIN,
  rightBreast: CLEAN_SKIN,
  nipples: CLEAN_SKIN,
  leftNipple: CLEAN_SKIN,
  rightNipple: CLEAN_SKIN,
  upperBack: CLEAN_SKIN,
  back: CLEAN_SKIN,
  spine: CLEAN_SKIN,
  lowerBack: CLEAN_SKIN,

  // Torso
  torso: { ...CLEAN_SKIN, intensity: 0.25 },
  abdomen: CLEAN_SKIN,
  navel: CLEAN_SKIN,
  leftSide: CLEAN_SKIN,
  rightSide: CLEAN_SKIN,
  waist: CLEAN_SKIN,
  hips: CLEAN_SKIN,
  leftHip: CLEAN_SKIN,
  rightHip: CLEAN_SKIN,
  pelvis: CLEAN_SKIN,

  // Arms
  armpits: NEUTRAL_FAINT,
  leftArmpit: NEUTRAL_FAINT,
  rightArmpit: NEUTRAL_FAINT,
  arms: CLEAN_SKIN,
  leftArm: CLEAN_SKIN,
  rightArm: CLEAN_SKIN,
  leftUpperArm: CLEAN_SKIN,
  rightUpperArm: CLEAN_SKIN,
  leftElbow: CLEAN_SKIN,
  rightElbow: CLEAN_SKIN,
  leftForearm: CLEAN_SKIN,
  rightForearm: CLEAN_SKIN,
  leftWrist: CLEAN_SKIN,
  rightWrist: CLEAN_SKIN,
  hands: CLEAN_SKIN,
  leftHand: CLEAN_SKIN,
  rightHand: CLEAN_SKIN,
  leftPalm: CLEAN_SKIN,
  rightPalm: CLEAN_SKIN,
  leftFingers: CLEAN_SKIN,
  rightFingers: CLEAN_SKIN,

  // Groin
  groin: NEUTRAL_FAINT,
  buttocks: NEUTRAL_FAINT,
  leftButtock: NEUTRAL_FAINT,
  rightButtock: NEUTRAL_FAINT,
  anus: NEUTRAL_FAINT,
  penis: NEUTRAL_FAINT,
  vagina: NEUTRAL_FAINT,

  // Legs
  legs: CLEAN_SKIN,
  leftLeg: CLEAN_SKIN,
  rightLeg: CLEAN_SKIN,
  thighs: CLEAN_SKIN,
  leftThigh: CLEAN_SKIN,
  rightThigh: CLEAN_SKIN,
  knees: CLEAN_SKIN,
  leftKnee: CLEAN_SKIN,
  rightKnee: CLEAN_SKIN,
  calves: CLEAN_SKIN,
  leftCalf: CLEAN_SKIN,
  rightCalf: CLEAN_SKIN,
  leftShin: CLEAN_SKIN,
  rightShin: CLEAN_SKIN,

  // Feet
  ankles: CLEAN_SKIN,
  leftAnkle: CLEAN_SKIN,
  rightAnkle: CLEAN_SKIN,
  feet: NEUTRAL_FAINT,
  leftFoot: NEUTRAL_FAINT,
  rightFoot: NEUTRAL_FAINT,
  leftHeel: NEUTRAL_FAINT,
  rightHeel: NEUTRAL_FAINT,
  leftSole: NEUTRAL_FAINT,
  rightSole: NEUTRAL_FAINT,
  leftArch: NEUTRAL_FAINT,
  rightArch: NEUTRAL_FAINT,

  // Toes
  toes: NEUTRAL_FAINT,
  leftBigToe: NEUTRAL_FAINT,
  leftSecondToe: NEUTRAL_FAINT,
  leftMiddleToe: NEUTRAL_FAINT,
  leftFourthToe: NEUTRAL_FAINT,
  leftLittleToe: NEUTRAL_FAINT,
  rightBigToe: NEUTRAL_FAINT,
  rightSecondToe: NEUTRAL_FAINT,
  rightMiddleToe: NEUTRAL_FAINT,
  rightFourthToe: NEUTRAL_FAINT,
  rightLittleToe: NEUTRAL_FAINT,
};

type HygieneLevelMap<T> = Record<HygieneLevel, T>;

/**
 * Hygiene-level scent modifiers for hygiene-modulated regions.
 *
 * These are intentionally high-level and can be refined later; they should stay
 * safe and non-explicit.
 */
export const HYGIENE_SCENT_MODIFIERS: Record<
  (typeof SCENT_TIERS)['hygieneModulated'][number],
  HygieneLevelMap<Partial<RegionScent>>
> = {
  hair: {
    0: { primary: 'fresh shampoo', intensity: 0.25 },
    1: { primary: 'clean hair', intensity: 0.3 },
    2: { primary: 'slightly stale hair', intensity: 0.35 },
    3: { primary: 'oily hair', intensity: 0.45 },
    4: { primary: 'sour hair', intensity: 0.6 },
    5: { primary: 'rank hair', intensity: 0.75 },
    6: { primary: 'putrid hair', intensity: 0.9 },
  },
  armpits: {
    0: { primary: 'fresh', intensity: 0.1 },
    1: { primary: 'faint musk', intensity: 0.2 },
    2: { primary: 'body odor', intensity: 0.4 },
    3: { primary: 'strong sweat', intensity: 0.6 },
    4: { primary: 'pungent', intensity: 0.75 },
    5: { primary: 'overpowering', intensity: 0.9 },
    6: { primary: 'putrid', intensity: 1.0 },
  },
  leftArmpit: {
    0: { primary: 'fresh', intensity: 0.1 },
    1: { primary: 'faint musk', intensity: 0.2 },
    2: { primary: 'body odor', intensity: 0.4 },
    3: { primary: 'strong sweat', intensity: 0.6 },
    4: { primary: 'pungent', intensity: 0.75 },
    5: { primary: 'overpowering', intensity: 0.9 },
    6: { primary: 'putrid', intensity: 1.0 },
  },
  rightArmpit: {
    0: { primary: 'fresh', intensity: 0.1 },
    1: { primary: 'faint musk', intensity: 0.2 },
    2: { primary: 'body odor', intensity: 0.4 },
    3: { primary: 'strong sweat', intensity: 0.6 },
    4: { primary: 'pungent', intensity: 0.75 },
    5: { primary: 'overpowering', intensity: 0.9 },
    6: { primary: 'putrid', intensity: 1.0 },
  },
  groin: {
    0: { primary: 'fresh', intensity: 0.1 },
    1: { primary: 'warm musk', intensity: 0.25 },
    2: { primary: 'stale musk', intensity: 0.45 },
    3: { primary: 'strong musk', intensity: 0.6 },
    4: { primary: 'pungent', intensity: 0.75 },
    5: { primary: 'overpowering', intensity: 0.9 },
    6: { primary: 'putrid', intensity: 1.0 },
  },
  buttocks: {
    0: { primary: 'fresh', intensity: 0.1 },
    1: { primary: 'stale skin', intensity: 0.25 },
    2: { primary: 'sweaty skin', intensity: 0.45 },
    3: { primary: 'strong sweat', intensity: 0.6 },
    4: { primary: 'pungent', intensity: 0.75 },
    5: { primary: 'overpowering', intensity: 0.9 },
    6: { primary: 'putrid', intensity: 1.0 },
  },
  leftButtock: {
    0: { primary: 'fresh', intensity: 0.1 },
    1: { primary: 'stale skin', intensity: 0.25 },
    2: { primary: 'sweaty skin', intensity: 0.45 },
    3: { primary: 'strong sweat', intensity: 0.6 },
    4: { primary: 'pungent', intensity: 0.75 },
    5: { primary: 'overpowering', intensity: 0.9 },
    6: { primary: 'putrid', intensity: 1.0 },
  },
  rightButtock: {
    0: { primary: 'fresh', intensity: 0.1 },
    1: { primary: 'stale skin', intensity: 0.25 },
    2: { primary: 'sweaty skin', intensity: 0.45 },
    3: { primary: 'strong sweat', intensity: 0.6 },
    4: { primary: 'pungent', intensity: 0.75 },
    5: { primary: 'overpowering', intensity: 0.9 },
    6: { primary: 'putrid', intensity: 1.0 },
  },
  feet: {
    0: { primary: 'fresh', intensity: 0.1 },
    1: { primary: 'faintly sweaty', intensity: 0.25 },
    2: { primary: 'stale sweat', intensity: 0.45 },
    3: { primary: 'strong foot odor', intensity: 0.65 },
    4: { primary: 'pungent foot odor', intensity: 0.8 },
    5: { primary: 'overpowering', intensity: 0.9 },
    6: { primary: 'putrid', intensity: 1.0 },
  },
  leftFoot: {
    0: { primary: 'fresh', intensity: 0.1 },
    1: { primary: 'faintly sweaty', intensity: 0.25 },
    2: { primary: 'stale sweat', intensity: 0.45 },
    3: { primary: 'strong foot odor', intensity: 0.65 },
    4: { primary: 'pungent foot odor', intensity: 0.8 },
    5: { primary: 'overpowering', intensity: 0.95 },
    6: { primary: 'putrid', intensity: 1.0 },
  },
  rightFoot: {
    0: { primary: 'fresh', intensity: 0.1 },
    1: { primary: 'faintly sweaty', intensity: 0.25 },
    2: { primary: 'stale sweat', intensity: 0.45 },
    3: { primary: 'strong foot odor', intensity: 0.65 },
    4: { primary: 'pungent foot odor', intensity: 0.8 },
    5: { primary: 'overpowering', intensity: 0.9 },
    6: { primary: 'putrid', intensity: 1.0 },
  },
  toes: {
    0: { primary: 'fresh', intensity: 0.1 },
    1: { primary: 'faintly sweaty', intensity: 0.25 },
    2: { primary: 'stale sweat', intensity: 0.45 },
    3: { primary: 'strong foot odor', intensity: 0.65 },
    4: { primary: 'pungent foot odor', intensity: 0.8 },
    5: { primary: 'overpowering', intensity: 0.9 },
    6: { primary: 'putrid', intensity: 1.0 },
  },
  leftBigToe: {
    0: { primary: 'fresh', intensity: 0.1 },
    1: { primary: 'faintly sweaty', intensity: 0.25 },
    2: { primary: 'stale sweat', intensity: 0.45 },
    3: { primary: 'strong foot odor', intensity: 0.65 },
    4: { primary: 'pungent foot odor', intensity: 0.8 },
    5: { primary: 'overpowering', intensity: 0.95 },
    6: { primary: 'putrid', intensity: 1.0 },
  },
  leftSecondToe: {
    0: { primary: 'fresh', intensity: 0.1 },
    1: { primary: 'faintly sweaty', intensity: 0.25 },
    2: { primary: 'stale sweat', intensity: 0.45 },
    3: { primary: 'strong foot odor', intensity: 0.65 },
    4: { primary: 'pungent foot odor', intensity: 0.8 },
    5: { primary: 'overpowering', intensity: 0.9 },
    6: { primary: 'putrid', intensity: 1.0 },
  },
  leftMiddleToe: {
    0: { primary: 'fresh', intensity: 0.1 },
    1: { primary: 'faintly sweaty', intensity: 0.25 },
    2: { primary: 'stale sweat', intensity: 0.45 },
    3: { primary: 'strong foot odor', intensity: 0.65 },
    4: { primary: 'pungent foot odor', intensity: 0.8 },
    5: { primary: 'overpowering', intensity: 0.9 },
    6: { primary: 'putrid', intensity: 1.0 },
  },
  leftFourthToe: {
    0: { primary: 'fresh', intensity: 0.1 },
    1: { primary: 'faintly sweaty', intensity: 0.25 },
    2: { primary: 'stale sweat', intensity: 0.45 },
    3: { primary: 'strong foot odor', intensity: 0.65 },
    4: { primary: 'pungent foot odor', intensity: 0.8 },
    5: { primary: 'overpowering', intensity: 0.9 },
    6: { primary: 'putrid', intensity: 1.0 },
  },
  leftLittleToe: {
    0: { primary: 'fresh', intensity: 0.1 },
    1: { primary: 'faintly sweaty', intensity: 0.25 },
    2: { primary: 'stale sweat', intensity: 0.45 },
    3: { primary: 'strong foot odor', intensity: 0.65 },
    4: { primary: 'pungent foot odor', intensity: 0.8 },
    5: { primary: 'overpowering', intensity: 0.9 },
    6: { primary: 'putrid', intensity: 1.0 },
  },
  rightBigToe: {
    0: { primary: 'fresh', intensity: 0.1 },
    1: { primary: 'faintly sweaty', intensity: 0.25 },
    2: { primary: 'stale sweat', intensity: 0.45 },
    3: { primary: 'strong foot odor', intensity: 0.65 },
    4: { primary: 'pungent foot odor', intensity: 0.8 },
    5: { primary: 'overpowering', intensity: 0.9 },
    6: { primary: 'putrid', intensity: 1.0 },
  },
  rightSecondToe: {
    0: { primary: 'fresh', intensity: 0.1 },
    1: { primary: 'faintly sweaty', intensity: 0.25 },
    2: { primary: 'stale sweat', intensity: 0.45 },
    3: { primary: 'strong foot odor', intensity: 0.65 },
    4: { primary: 'pungent foot odor', intensity: 0.8 },
    5: { primary: 'overpowering', intensity: 0.9 },
    6: { primary: 'putrid', intensity: 1.0 },
  },
  rightMiddleToe: {
    0: { primary: 'fresh', intensity: 0.1 },
    1: { primary: 'faintly sweaty', intensity: 0.25 },
    2: { primary: 'stale sweat', intensity: 0.45 },
    3: { primary: 'strong foot odor', intensity: 0.65 },
    4: { primary: 'pungent foot odor', intensity: 0.8 },
    5: { primary: 'overpowering', intensity: 0.9 },
    6: { primary: 'putrid', intensity: 1.0 },
  },
  rightFourthToe: {
    0: { primary: 'fresh', intensity: 0.1 },
    1: { primary: 'faintly sweaty', intensity: 0.25 },
    2: { primary: 'stale sweat', intensity: 0.45 },
    3: { primary: 'strong foot odor', intensity: 0.65 },
    4: { primary: 'pungent foot odor', intensity: 0.8 },
    5: { primary: 'overpowering', intensity: 0.9 },
    6: { primary: 'putrid', intensity: 1.0 },
  },
  rightLittleToe: {
    0: { primary: 'fresh', intensity: 0.1 },
    1: { primary: 'faintly sweaty', intensity: 0.25 },
    2: { primary: 'stale sweat', intensity: 0.45 },
    3: { primary: 'strong foot odor', intensity: 0.65 },
    4: { primary: 'pungent foot odor', intensity: 0.8 },
    5: { primary: 'overpowering', intensity: 0.9 },
    6: { primary: 'putrid', intensity: 1.0 },
  },
};
